# Generated by Django 6.0.5 on 2026-05-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_remove_company_crm_company_domain_9af8a8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='projects_pr_title_ba614c_idx'), models.Index(fields=['company'], name='projects_pr_company_3a6b2a_idx'), models.Index(fields=['contact'], name='projects_pr_contact_c032c7_idx'), models.Index(fields=['deleted_at'], name='projects_pr_deleted_4c0d8c_idx'), models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx')],
            },
        ),
    ]
