# Generated by Django 6.0.5 on 2026-05-27 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_alter_contact_salutation'),
        ('projects', '0004_project_project_number_project_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='projects.project')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['activity_id'], name='activities__activit_a4cb1c_idx'), models.Index(fields=['contact'], name='activities__contact_9b9b6b_idx'), models.Index(fields=['company'], name='activities__company_8b92d2_idx'), models.Index(fields=['project'], name='activities__project_ce6ed3_idx'), models.Index(fields=['activity_type'], name='activities__activit_8e7970_idx'), models.Index(fields=['occurred_at'], name='activities__occurre_981c70_idx'), models.Index(fields=['created_by'], name='activities__created_8db573_idx'), models.Index(fields=['deleted_at'], name='activities__deleted_783a77_idx'), models.Index(fields=['created_at'], name='activities__created_0e5d3c_idx')],
            },
        ),
    ]
