# Generated by Django 6.0.5 on 2026-05-27 08:28

import django.db.models.deletion
import documents.models.document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_remove_company_crm_company_domain_9af8a8_idx_and_more'),
        ('projects', '0003_project_assigned_to'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=documents.models.document._document_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.contact')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_id'], name='documents_d_documen_612cf4_idx'), models.Index(fields=['title'], name='documents_d_title_ccf306_idx'), models.Index(fields=['company'], name='documents_d_company_2b1982_idx'), models.Index(fields=['contact'], name='documents_d_contact_09f1b4_idx'), models.Index(fields=['project'], name='documents_d_project_43ce81_idx'), models.Index(fields=['task'], name='documents_d_task_id_c8f201_idx'), models.Index(fields=['uploaded_by'], name='documents_d_uploade_6455fb_idx'), models.Index(fields=['mime_type'], name='documents_d_mime_ty_29cc61_idx'), models.Index(fields=['deleted_at'], name='documents_d_deleted_135b7b_idx'), models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx')],
            },
        ),
    ]
