# Generated by Django 6.0.5 on 2026-05-27 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company_domain_company_uid_number_company_vat_number_and_more'),
        ('documents', '0001_initial'),
        ('projects', '0004_project_project_number_project_status_and_more'),
        ('tasks', '0002_task_priority_task_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('contract', 'Contract'), ('certificate', 'Certificate'), ('invoice', 'Invoice'), ('photo', 'Photo'), ('customer_file', 'Customer File'), ('internal', 'Internal'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_d_categor_2c6923_idx'),
        ),
    ]
