# Generated by Django 6.0.5 on 2026-05-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('company_type', models.CharField(choices=[('prospect', 'Prospect'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('partner', 'Partner'), ('other', 'Other')], default='prospect', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('duplicate', 'Duplicate')], default='active', max_length=50)),
                ('main_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=120)),
                ('state_region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Switzerland', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['postal_code'], name='crm_address_postal__81635f_idx'), models.Index(fields=['city'], name='crm_address_city_704518_idx'), models.Index(fields=['country'], name='crm_address_country_f5cdc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hq', 'HQ'), ('office', 'Office'), ('branch', 'Branch'), ('warehouse', 'Warehouse'), ('billing', 'Billing'), ('other', 'Other')], default='office', max_length=50)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_locations', to='crm.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='crm.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='hq_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.companylocation'),
        ),
        migrations.CreateModel(
            name='CompanyPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('main', 'Main'), ('sales', 'Sales'), ('support', 'Support'), ('finance', 'Finance'), ('it', 'IT'), ('other', 'Other')], default='main', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='crm.companylocation')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('left_company', 'Left Company'), ('archived', 'Archived'), ('do_not_contact', 'Do Not Contact')], default='active', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company')),
                ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.companylocation')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('work', 'Work'), ('private', 'Private'), ('other', 'Other')], default='work', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('mobile', 'Mobile'), ('work', 'Work'), ('private', 'Private'), ('other', 'Other')], default='mobile', max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm.contact')),
            ],
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['company'], name='crm_company_company_8e4008_idx'),
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['type'], name='crm_company_type_39e330_idx'),
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['is_headquarters'], name='crm_company_is_head_1ee862_idx'),
        ),
        migrations.AddConstraint(
            model_name='companylocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_headquarters', True)), fields=('company',), name='unique_company_hq'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='crm_company_name_895a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='crm_company_domain_9af8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='crm_company_status_6bb2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_type'], name='crm_company_company_a05006_idx'),
        ),
        migrations.AddIndex(
            model_name='companyphonenumber',
            index=models.Index(fields=['company'], name='crm_company_company_633357_idx'),
        ),
        migrations.AddIndex(
            model_name='companyphonenumber',
            index=models.Index(fields=['location'], name='crm_company_locatio_11ff7e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyphonenumber',
            index=models.Index(fields=['phone_number'], name='crm_company_phone_n_a415ba_idx'),
        ),
        migrations.AddIndex(
            model_name='companyphonenumber',
            index=models.Index(fields=['is_primary'], name='crm_company_is_prim_141c80_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyphonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company',), name='unique_company_primary_phone'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_cda0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company'], name='crm_contact_company_bd8786_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['work_location'], name='crm_contact_work_lo_79ff3a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status'], name='crm_contact_status_520462_idx'),
        ),
        migrations.AddIndex(
            model_name='contactemailaddress',
            index=models.Index(fields=['email'], name='crm_contact_email_68e3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='contactemailaddress',
            index=models.Index(fields=['contact'], name='crm_contact_contact_de9a75_idx'),
        ),
        migrations.AddIndex(
            model_name='contactemailaddress',
            index=models.Index(fields=['is_primary'], name='crm_contact_is_prim_81e301_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactemailaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact',), name='unique_contact_primary_email'),
        ),
        migrations.AddIndex(
            model_name='contactphonenumber',
            index=models.Index(fields=['contact'], name='crm_contact_contact_fc6c18_idx'),
        ),
        migrations.AddIndex(
            model_name='contactphonenumber',
            index=models.Index(fields=['phone_number'], name='crm_contact_phone_n_9a43cc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactphonenumber',
            index=models.Index(fields=['is_primary'], name='crm_contact_is_prim_e7ee84_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactphonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact',), name='unique_contact_primary_phone'),
        ),
    ]
