# Generated by Django 6.0.5 on 2026-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='crm_company_domain_9af8a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crm_contact_work_lo_79ff3a_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('herr', 'Herr'), ('frau', 'Frau'), ('divers', 'Divers')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='company',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_location',
        ),
    ]
