# Generated by Django 6.0.5 on 2026-05-27 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_company_crm_company_domain_9af8a8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='uid_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.companylocation'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='crm_company_domain_9af8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['work_location'], name='crm_contact_work_lo_79ff3a_idx'),
        ),
    ]
