# Generated by Django 6.0.5 on 2026-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company_domain_company_uid_number_company_vat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('herr', 'Mr.'), ('frau', 'Mrs.'), ('divers', 'Unknown')], max_length=10),
        ),
    ]
